version: "3.9"

services:

  backend:
    container_name: obedy_backend
    restart: always
    build:
      context: ./backend
      extra_hosts:
        - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env
    networks:
      - default
    ports:
      - "8000:8000"

  frontend:
    container_name: obedy_frontend
    restart: always
    build:
      context: ./frontend
    networks:
      - default
    ports:
      - "3000:3000"

networks:
  default:
